### ISSUE TITLE
[BUG] Button SendMessage

### ISSUE THREAD

**Issue by ilhamn2405** [WhiskeySockets/Baileys#62] opened 2023-05-12 20:49 UTC
![1683923992-picsay](https://github.com/WhiskeySockets/Baileys/assets/43334234/3f0fa4bb-9a25-478d-9b8b-7791eefd271a)
Saya menambahkan button di fitur isCmd, pesan di terima, tetapi tidak ada respon apapun (⁠╯⁠︵⁠╰⁠,⁠)

**Comment by andresayac** [comment] 2023-05-12 21:15
this is already duplicated refer to
https://github.com/WhiskeySockets/Baileys/issues/56

**Comment by ilhamn2405** [comment] 2023-05-13 13:23
> ini sudah digandakan merujuk ke #56

Means for now there is no solution?

**Comment by andresayac** [comment] 2023-05-14 00:20
no friend for now, separators have recommended not to depend on this solution

**Comment by edgardmessias** [comment] 2023-05-24 01:17
Duplicate of #56

**Closed by edgardmessias** 2023-05-24 01:17 UTC
Labels: bug

**Comment by ryugenxd** [comment] 2023-05-24 02:10
> > ini sudah digandakan merujuk ke #56
> 
> Means for now there is no solution?

>meng kadang", w asah ni parang  ```git pull```

**Comment by WatanabeThiago** [comment] 2024-09-28 00:07
I'm waiting for this feature.
