### ISSUE TITLE
NPM 

### ISSUE THREAD

**Issue by Teamolduser** [WhiskeySockets/Baileys#37] opened 2023-04-30 08:33 UTC
Can Anyone Upload This Modules In Npmjs.com 

I Tried But Its Giving Error Of tsc and typedoc

**Comment by andresayac** [comment] 2023-04-30 13:21
I have not had a problem generating the package. Be careful, I do not rule out that it is not like that, I am new

![image](https://user-images.githubusercontent.com/16548795/235355038-d18dbcfd-c1da-4ad4-bbf2-6330dc844979.png)
![image](https://user-images.githubusercontent.com/16548795/235355047-32db61a9-8b25-4a2b-9867-086345a8374d.png)

**Comment by Teamolduser** [comment] 2023-04-30 13:33
> I have not had a problem generating the package. Be careful, I do not rule out that it is not like that, I am new
> 
> https://github.com/WhiskeySockets/Baileys/blob/master/.github/workflows/publish-release.yml
> 
> ![image](https://user-images.githubusercontent.com/16548795/235355038-d18dbcfd-c1da-4ad4-bbf2-6330dc844979.png) ![image](https://user-images.githubusercontent.com/16548795/235355047-32db61a9-8b25-4a2b-9867-086345a8374d.png)

Can i public in my npm

**Comment by Teamolduser** [comment] 2023-05-02 20:59
> I have not had a problem generating the package. Be careful, I do not rule out that it is not like that, I am new
> 
> https://github.com/WhiskeySockets/Baileys/blob/master/.github/workflows/publish-release.yml
> 
> ![image](https://user-images.githubusercontent.com/16548795/235355038-d18dbcfd-c1da-4ad4-bbf2-6330dc844979.png) ![image](https://user-images.githubusercontent.com/16548795/235355047-32db61a9-8b25-4a2b-9867-086345a8374d.png)

how can i publish @adiwajshing/baileys@4.4.0 in my npm  after i clone from npm of @adiwajshin/baileys@4.4.0

**Comment by andresayac** [comment] 2023-05-02 21:44
you don't need to use the npmjs.com package you can use yarn add **github:WhiskeySockets/Baileys** instead while the release is being fixed

**Comment by Teamolduser** [comment] 2023-05-02 22:04
> you don't need to use the npmjs.com package you can use yarn add **github:WhiskeySockets/Baileys** instead while the release is being fixed

but i want a single auth  one system so i ask to you

**Comment by andresayac** [comment] 2023-05-02 22:48
The truth is that I have not understood very well, when you say single auth

**Comment by dhirennjaypal** [comment] 2023-05-03 03:59
I used to use this module via require()
but it no longer works
i gives me this error 
`
Cannot find module '...\node_modules\@adiwajshing\baileys\lib\index.js'
`
github:WhiskeySockets/Baileys

**Comment by andresayac** [comment] 2023-05-03 04:22
> I used to use this module via require()
> but it no longer works
> i gives me this error 
> `
> Cannot find module '...\node_modules\@adiwajshing\baileys\lib\index.js'
> `

share screenshot of your package.json

**Comment by Teamolduser** [comment] 2023-05-03 07:37
> > you don't need to use the npmjs.com package you can use yarn add **github:WhiskeySockets/Baileys** instead while the release is being fixed
> 
> but i want a single auth one system so i ask to you

but i want so how can i upload 4.4.0 in my npm

**Comment by choopchik** [comment] 2023-05-03 20:02
> > I used to use this module via require()
> > but it no longer works
> > i gives me this error
> > `Cannot find module '...\node_modules\@adiwajshing\baileys\lib\index.js'`
> 
> share screenshot of your package.json

![image](https://user-images.githubusercontent.com/93326408/236034627-00b34e56-2d9d-4903-b582-52875a2821d3.png)

`Error: Cannot find module '/home/user/dev/wa-desktop/node_modules/@adiwajshing/baileys/lib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:416:19)
    at Module._findPath (node:internal/modules/cjs/loader:658:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1040:27)
    at o._resolveFilename (node:electron/js2c/renderer_init:2:3879)
    at Module._load (node:internal/modules/cjs/loader:900:27)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1120:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/user/dev/assitant-desktop/app/view_preload.js:3:26)
(`

**Comment by Teamolduser** [comment] 2023-05-03 20:22
> I used to use this module via require() but it no longer works i gives me this error `Cannot find module '...\node_modules\@adiwajshing\baileys\lib\index.js'`

From where you clone or download this

**Comment by choopchik** [comment] 2023-05-03 20:24
> > I used to use this module via require() but it no longer works i gives me this error `Cannot find module '...\node_modules\@adiwajshing\baileys\lib\index.js'`
> 
> From where you clone or download this

`yarn add github:WhiskeySockets/Baileys`

**Comment by Teamolduser** [comment] 2023-05-03 20:35
> > > I used to use this module via require() but it no longer works i gives me this error `Cannot find module '...\node_modules\@adiwajshing\baileys\lib\index.js'`
> > 
> > 
> > From where you clone or download this
> 
> `yarn add github:WhiskeySockets/Baileys`

in which bot

**Comment by choopchik** [comment] 2023-05-03 20:37
> in which bot

Don't understand the question (?)

**Comment by Teamolduser** [comment] 2023-05-03 20:39
> > in which bot
> 
> Don't understand the question (?)

In which folder you cloned or download it

**Comment by choopchik** [comment] 2023-05-03 20:56
I ran `yarn add github:WhiskeySockets/Baileys` from the top folder of the project.

**Comment by Teamolduser** [comment] 2023-05-03 21:00
> I ran `yarn add github:WhiskeySockets/Baileys` from the top folder of the project.

Can you give a folder link ?

**Comment by choopchik** [comment] 2023-05-03 21:06
Folder link?, you mean: `/home/user/dev/wa-desktop/`


In the error message, it says:
`Cannot find module '...\node_modules\@adiwajshing\baileys\lib\index.js'

But when looking at the Baileys files inside node_modules, the 'lib\index.js' file isn't there. Could this be because Baileys uses TypeScript (.ts) while my project is in JavaScript (.js)?
screenshot:
![image](https://user-images.githubusercontent.com/93326408/236048716-43ed053e-e2f9-4a14-80d9-2d6beb885139.png)

**Comment by Teamolduser** [comment] 2023-05-03 21:18
> const { makeWASocket } = require('@adiwajshing/baileys');

const { makeWASocket } = require('@adiwajshing/baileys');.default

**Comment by choopchik** [comment] 2023-05-03 21:19
changed to ` const { makeWASocket } = require('@adiwajshing/baileys');`
Still getting the same error:

```
Error: Cannot find module '/home/user/dev/wa-desktop/node_modules/@adiwajshing/baileys/lib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:416:19)
    at Module._findPath (node:internal/modules/cjs/loader:658:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1040:27)
    at o._resolveFilename (node:electron/js2c/renderer_init:2:3879)
    at Module._load (node:internal/modules/cjs/loader:900:27)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1120:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/user/dev/assitant-desktop/app/view_preload.js:3:26)
(

**Comment by choopchik** [comment] 2023-05-03 21:21
This is the package.json of my Baileys:
```
{
  "name": "@adiwajshing/baileys",
  "version": "5.0.0",
  "description": "WhatsApp API",
  "homepage": "https://github.com/adiwajshing/Baileys",
  "main": "lib/index.js",
  "types": "lib/index.d.ts",
  "keywords": [
    "whatsapp",
    "js-whatsapp",
    "whatsapp-api",
    "whatsapp-web",
    "whatsapp",
    "whatsapp-chat",
    "whatsapp-group",
    "automation",
    "multi-device"
  ],
  "scripts": {
    "test": "jest",
    "prepare": "tsc",
    "build:all": "tsc && typedoc",
    "build:docs": "typedoc",
    "build:tsc": "tsc",
    "example": "node --inspect -r ts-node/register Example/example.ts",
    "gen:protobuf": "sh WAProto/GenerateStatics.sh",
    "lint": "eslint . --ext .js,.ts,.jsx,.tsx",
    "lint:fix": "eslint . --fix --ext .js,.ts,.jsx,.tsx"
  },
  "author": "Adhiraj Singh",
  "license": "MIT",
  "repository": {
    "url": "git@github.com:adiwajshing/baileys.git"
  },
  "dependencies": {
    "@hapi/boom": "^9.1.3",
    "axios": "^1.3.3",
    "futoin-hkdf": "^1.5.1",
    "libsignal": "https://github.com/adiwajshing/libsignal-node.git",
    "music-metadata": "^7.12.3",
    "node-cache": "^5.1.2",
    "pino": "^7.0.0",
    "protobufjs": "^6.11.3",
    "ws": "^8.0.0"
  },
  "peerDependencies": {
    "@adiwajshing/keyed-db": "^0.2.4",
    "jimp": "^0.16.1",
    "link-preview-js": "^3.0.0",
    "qrcode-terminal": "^0.12.0",
    "sharp": "^0.30.5"
  },
  "peerDependenciesMeta": {
    "@adiwajshing/keyed-db": {
      "optional": true
    },
    "jimp": {
      "optional": true
    },
    "qrcode-terminal": {
      "optional": true
    },
    "sharp": {
      "optional": true
    },
    "link-preview-js": {
      "optional": true
    }
  },
  "files": [
    "lib/*",
    "WAProto/*",
    "WASignalGroup/*.js"
  ],
  "devDependencies": {
    "@adiwajshing/eslint-config": "https://github.com/adiwajshing/eslint-config.git",
    "@adiwajshing/keyed-db": "^0.2.4",
    "@types/got": "^9.6.11",
    "@types/jest": "^27.5.1",
    "@types/node": "^16.0.0",
    "@types/sharp": "^0.29.4",
    "@types/ws": "^8.0.0",
    "eslint": "^8.0.0",
    "jest": "^27.0.6",
    "jimp": "^0.16.1",
    "link-preview-js": "^3.0.0",
    "qrcode-terminal": "^0.12.0",
    "sharp": "^0.30.5",
    "ts-jest": "^27.0.3",
    "ts-node": "^10.8.1",
    "typedoc": "^0.22.0",
    "typescript": "^4.0.0"
  }
}

**Comment by Teamolduser** [comment] 2023-05-03 21:22
``

> changed to ` const { makeWASocket } = require('@adiwajshing/baileys');` Still getting the same error:
> 
> ```
> Error: Cannot find module '/home/user/dev/wa-desktop/node_modules/@adiwajshing/baileys/lib/index.js'. Please verify that the package.json has a valid "main" entry
>     at tryPackage (node:internal/modules/cjs/loader:416:19)
>     at Module._findPath (node:internal/modules/cjs/loader:658:18)
>     at Module._resolveFilename (node:internal/modules/cjs/loader:1040:27)
>     at o._resolveFilename (node:electron/js2c/renderer_init:2:3879)
>     at Module._load (node:internal/modules/cjs/loader:900:27)
>     at f._load (node:electron/js2c/asar_bundle:2:13330)
>     at o._load (node:electron/js2c/renderer_init:2:3109)
>     at Module.require (node:internal/modules/cjs/loader:1120:19)
>     at require (node:internal/modules/cjs/helpers:103:18)
>     at Object.<anonymous> (/home/user/dev/assitant-desktop/app/view_preload.js:3:26)
> (
> ```

use yarn add @adiwajshing/baileys@github:WhiskeySockets

**Comment by choopchik** [comment] 2023-05-03 21:23
```
$ yarn add @adiwajshing/baileys@github:WhiskeySockets
yarn add v1.22.19
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
error Invalid hosted git fragment "github:WhiskeySockets".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by Teamolduser** [comment] 2023-05-03 21:25
> ```
> $ yarn add @adiwajshing/baileys@github:WhiskeySockets
> yarn add v1.22.19
> warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
> [1/4] Resolving packages...
> error Invalid hosted git fragment "github:WhiskeySockets".
> info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
> ```

try to run with npm i @adiwajshing/baileys@github:WhiskeySockets

**Comment by choopchik** [comment] 2023-05-03 21:27
```
$ npm i @adiwajshing/baileys@github:WhiskeySockets
npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/null/WhiskeySockets.git
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2023-05-03T21_27_16_831Z-debug-0.log

**Comment by Teamolduser** [comment] 2023-05-03 21:28
> ```
> $ npm i @adiwajshing/baileys@github:WhiskeySockets
> npm ERR! code 128
> npm ERR! An unknown git error occurred
> npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/null/WhiskeySockets.git
> npm ERR! git@github.com: Permission denied (publickey).
> npm ERR! fatal: Could not read from remote repository.
> npm ERR! 
> npm ERR! Please make sure you have the correct access rights
> npm ERR! and the repository exists.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/user/.npm/_logs/2023-05-03T21_27_16_831Z-debug-0.log
> ```

can you told me what are you trying to do

**Comment by Teamolduser** [comment] 2023-05-03 21:31
> ```
> $ npm i @adiwajshing/baileys@github:WhiskeySockets
> npm ERR! code 128
> npm ERR! An unknown git error occurred
> npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/null/WhiskeySockets.git
> npm ERR! git@github.com: Permission denied (publickey).
> npm ERR! fatal: Could not read from remote repository.
> npm ERR! 
> npm ERR! Please make sure you have the correct access rights
> npm ERR! and the repository exists.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/user/.npm/_logs/2023-05-03T21_27_16_831Z-debug-0.log
> ```

try this yarn add @adiwajshing/baileys@github:WhiskeySockets/baileys

**Comment by choopchik** [comment] 2023-05-03 21:32
> can you told me what are you trying to do

To `require` Baileys into my project

**Comment by Teamolduser** [comment] 2023-05-03 21:32
> > can you told me what are you trying to do
> 
> To `require` Baileys into my project

which project

**Comment by choopchik** [comment] 2023-05-03 21:33
whatsapp desktop app using electron

**Comment by Teamolduser** [comment] 2023-05-03 21:35
> whatsapp desktop app using electron

oh

try this yarn add @adiwajshing/baileys@github:WhiskeySockets/baileys

if this will show trouble with network then use npm i instead of yarn add

**Comment by choopchik** [comment] 2023-05-03 21:37
still bring me the same error for `require`

```
ror: Cannot find module '/home/user/dev/wa-desktop/node_modules/@adiwajshing/baileys/lib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:416:19)
    at Module._findPath (node:internal/modules/cjs/loader:658:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1040:27)
    at o._resolveFilename (node:electron/js2c/renderer_init:2:3879)
    at Module._load (node:internal/modules/cjs/loader:900:27)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1120:19)
    at require (node:internal/modules/cjs/helpers:103:18)

**Comment by Teamolduser** [comment] 2023-05-03 21:41
> still brings me the same error for `require`
> 
> ```
> Eror: Cannot find module '/home/user/dev/wa-desktop/node_modules/@adiwajshing/baileys/lib/index.js'. Please verify that the package.json has a valid "main" entry
>     at tryPackage (node:internal/modules/cjs/loader:416:19)
>     at Module._findPath (node:internal/modules/cjs/loader:658:18)
>     at Module._resolveFilename (node:internal/modules/cjs/loader:1040:27)
>     at o._resolveFilename (node:electron/js2c/renderer_init:2:3879)
>     at Module._load (node:internal/modules/cjs/loader:900:27)
>     at f._load (node:electron/js2c/asar_bundle:2:13330)
>     at o._load (node:electron/js2c/renderer_init:2:3109)
>     at Module.require (node:internal/modules/cjs/loader:1120:19)
>     at require (node:internal/modules/cjs/helpers:103:18)
>  
> ```
First remove old @adiwajshing/baileys
Then try
yarn add @adiwajshing/baileys@github:WhiskeySockets/baileys

**Comment by choopchik** [comment] 2023-05-03 21:44
Did it. same error

Baileys, `package.json` file contains `"main": "lib/index.js",` but that file is clearly not present in the code

https://github.com/WhiskeySockets/Baileys/blob/master/package.json


I wonder why

**Comment by Teamolduser** [comment] 2023-05-03 21:46
> I have not had a problem generating the package. Be careful, I do not rule out that it is not like that, I am new
> 
> https://github.com/WhiskeySockets/Baileys/blob/master/.github/workflows/publish-release.yml
> 
> ![image](https://user-images.githubusercontent.com/16548795/235355038-d18dbcfd-c1da-4ad4-bbf2-6330dc844979.png) ![image](https://user-images.githubusercontent.com/16548795/235355047-32db61a9-8b25-4a2b-9867-086345a8374d.png)

Then i don't know ask to @PurpShell and  @andresayac

**Comment by Teamolduser** [comment] 2023-05-03 21:58
> Did it. same error
> 
> Baileys, `package.json` file contains `"main": "lib/index.js",` but that file is clearly not present in the code
> 
> https://github.com/WhiskeySockets/Baileys/blob/master/package.json
> 
> I wonder why

still having issue try yarn add @adiwajshing/baileys@npm:@queenanya/baileys@5.0.0

**Comment by PurpShell** [comment] 2023-05-04 02:58
We are working on this, we have an NPM org ready

**Comment by ahmedRSA** [comment] 2023-05-09 04:35
> We are working on this, we have an NPM org ready

Is there any update on when will you release it?

**Comment by jmedellinc** [comment] 2023-05-23 00:26
I had troubles as well using baileys in a CJS node project (using require() instead of IMPORT)

They way I solved is as follows

```
const makeWASocketCont = require("@whiskeysockets/baileys");
const makeWASocket = makeWASocketCont.default;
const { useMultiFileAuthState, DisconnectReason } = makeWASocketCont;
```

**Comment by Marcoant007** [comment] 2023-06-13 21:35
You don't need yarn anymore using the normal npm already get the latest version and it works perfectly.

https://www.npmjs.com/package/@whiskeysockets/baileys

**Closed** 2023-10-05 11:37 UTC

**Comment by Teamolduser** [comment] 2023-10-06 16:00
> You don't need yarn anymore using the normal npm already get the latest version and it works perfectly.
> 
> https://www.npmjs.com/package/@whiskeysockets/baileys

But how can u install module now a days npm has some issue than the other option is yarn to use

**Comment by Teamolduser** [comment] 2023-10-06 16:01
> I had troubles as well using baileys in a CJS node project (using require() instead of IMPORT)
> 
> They way I solved is as follows
> 
> ```
> const makeWASocketCont = require("@whiskeysockets/baileys");
> const makeWASocket = makeWASocketCont.default;
> const { useMultiFileAuthState, DisconnectReason } = makeWASocketCont;
> ```

You can use 
const makeWASocket = require("@whiskeysockets/baileys").default;

**Comment by Abdullasl321** [comment] 2024-06-01 03:55
> I had troubles as well using baileys in a CJS node project (using require() instead of IMPORT)
> 
> They way I solved is as follows
> 
> ```
> const makeWASocketCont = require("@whiskeysockets/baileys");
> const makeWASocket = makeWASocketCont.default;
> const { useMultiFileAuthState, DisconnectReason } = makeWASocketCont;
> ```

It Worked Thx Bro :-)
